# Training Data Trasformation

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
train_data = pd.read_csv("/content/churn-bigml-80.csv")
train_data.head()

State  Account length  Area code International plan Voice mail plan  \
0    KS             128        415                 No             Yes   
1    OH             107        415                 No             Yes   
2    NJ             137        415                 No              No   
3    OH              84        408                Yes              No   
4    OK              75        415                Yes              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             45.07              197.4               99             16.78   
1             27.47              195.5              103             16.62   
2             41.38              121.2              110             10.30   
3             50.90               61.9               88              5.26   
4             28.34              148.3              122             12.61   

   Total night minutes  Total night calls  Total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   Total intl minutes  Total intl calls  Total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   Customer service calls  Churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False

In [ ]:
columns = train_data.columns
row = len(train_data.index)
print(columns)
print(len(columns))
row

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='object')
20


2666

In [ ]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2666 entries, 0 to 2665
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   State                   2666 non-null   object 
 1   Account length          2666 non-null   int64  
 2   Area code               2666 non-null   int64  
 3   International plan      2666 non-null   object 
 4   Voice mail plan         2666 non-null   object 
 5   Number vmail messages   2666 non-null   int64  
 6   Total day minutes       2666 non-null   float64
 7   Total day calls         2666 non-null   int64  
 8   Total day charge        2666 non-null   float64
 9   Total eve minutes       2666 non-null   float64
 10  Total eve calls         2666 non-null   int64  
 11  Total eve charge        2666 non-null   float64
 12  Total night minutes     2666 non-null   float64
 13  Total night calls       2666 non-null   int64  
 14  Total night charge      2666 non-null   

In [ ]:
train_data.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [ ]:
unq_states = train_data["State"].unique()
print(unq_states)
print(train_data["International plan"].unique())
print(train_data["Voice mail plan"].unique())
print(train_data["Churn"].unique())
unq_states = list(unq_states)

['KS' 'OH' 'NJ' 'OK' 'AL' 'MA' 'MO' 'WV' 'RI' 'IA' 'MT' 'ID' 'VT' 'VA'
 'TX' 'FL' 'CO' 'AZ' 'NE' 'WY' 'IL' 'NH' 'LA' 'GA' 'AK' 'MD' 'AR' 'WI'
 'OR' 'DE' 'IN' 'UT' 'CA' 'SD' 'NC' 'WA' 'MN' 'NM' 'NV' 'DC' 'NY' 'KY'
 'ME' 'MS' 'MI' 'SC' 'TN' 'PA' 'HI' 'ND' 'CT']
['No' 'Yes']
['Yes' 'No']
[False  True]


## Feature Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_data["International plan"] = le.fit_transform(train_data["International plan"])
train_data["Voice mail plan"] = le.fit_transform(train_data["Voice mail plan"])
train_data["Churn"] = le.fit_transform(train_data["Churn"])

In [ ]:
print(train_data["International plan"].unique())
print(train_data["Voice mail plan"].unique())
print(train_data["Churn"].unique())

[0 1]
[1 0]
[0 1]


In [ ]:
temp = pd.get_dummies(train_data["State"])
train_data = pd.concat([train_data, temp],axis=1)
train_data.drop(["State"], axis = 1, inplace = True)

In [ ]:
train_data.head()

Account length  Area code  International plan  Voice mail plan  \
0             128        415                   0                1   
1             107        415                   0                1   
2             137        415                   0                0   
3              84        408                   1                0   
4              75        415                   1                0   

   Number vmail messages  Total day minutes  Total day calls  \
0                     25              265.1              110   
1                     26              161.6              123   
2                      0              243.4              114   
3                      0              299.4               71   
4                      0              166.7              113   

   Total day charge  Total eve minutes  Total eve calls  ...  SD  TN  TX  UT  \
0             45.07              197.4               99  ...   0   0   0   0   
1             27.47              195.5              103  ...   0   0   0   0   
2             41.38              121.2              110  ...   0   0   0   0   
3             50.90               61.9               88  ...   0   0   0   0   
4             28.34              148.3              122  ...   0   0   0   0   

   VA  VT  WA  WI  WV  WY  
0   0   0   0   0   0   0  
1   0   0   0   0   0   0  
2   0   0   0   0   0   0  
3   0   0   0   0   0   0  
4   0   0   0   0   0   0  

[5 rows x 70 columns]

## Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
unq_states.append("International plan")
unq_states.append("Voice mail plan")
scale_col = train_data.drop(unq_states, axis = 1).columns
train_data[scale_col] = scaler.fit_transform(train_data[scale_col])

In [ ]:
train_data.head()

Account length  Area code  International plan  Voice mail plan  \
0        0.524793   0.068627                   0                1   
1        0.438017   0.068627                   0                1   
2        0.561983   0.068627                   0                0   
3        0.342975   0.000000                   1                0   
4        0.305785   0.068627                   1                0   

   Number vmail messages  Total day minutes  Total day calls  \
0                   0.50           0.755701          0.68750   
1                   0.52           0.460661          0.76875   
2                   0.00           0.693843          0.71250   
3                   0.00           0.853478          0.44375   
4                   0.00           0.475200          0.70625   

   Total day charge  Total eve minutes  Total eve calls  ...  SD  TN  TX  UT  \
0          0.755701           0.542755         0.582353  ...   0   0   0   0   
1          0.460597           0.537531         0.605882  ...   0   0   0   0   
2          0.693830           0.333242         0.647059  ...   0   0   0   0   
3          0.853454           0.170195         0.517647  ...   0   0   0   0   
4          0.475184           0.407754         0.717647  ...   0   0   0   0   

   VA  VT  WA  WI  WV  WY  
0   0   0   0   0   0   0  
1   0   0   0   0   0   0  
2   0   0   0   0   0   0  
3   0   0   0   0   0   0  
4   0   0   0   0   0   0  

[5 rows x 70 columns]

## Spliting Data

In [ ]:
X_train = train_data.iloc[:, :-1].values
y_train = train_data.iloc[:, -1].values

In [ ]:
X_train[:1]

array([[0.52479339, 0.06862745, 0.        , 1.        , 0.5       ,
        0.75570125, 0.6875    , 0.75570087, 0.54275502, 0.58235294,
        0.54286639, 0.57216055, 0.43609023, 0.5721519 , 0.5       ,
        0.15      , 0.5       , 0.11111111, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]])

In [ ]:
y_train[:5]

array([0, 0, 0, 0, 0], dtype=uint8)

## Train Regression Model

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
training_result = model.predict(X_train)

## Train Results

In [ ]:
cm = confusion_matrix(y_train, training_result)
acc = accuracy_score(y_train, training_result)

print(f"TRAINING RESULTS : \n {cm} \nAccuracy : {acc*100}%")

TRAINING RESULTS : 
 [[2600    0]
 [  66    0]] 
 97.52438109527381%


# Test Data

In [ ]:
test_data = pd.read_csv("/content/churn-bigml-20.csv")
test_data.head()

State  Account length  Area code International plan Voice mail plan  \
0    LA             117        408                 No              No   
1    IN              65        415                 No              No   
2    NY             161        415                 No              No   
3    SC             111        415                 No              No   
4    HI              49        510                 No              No   

   Number vmail messages  Total day minutes  Total day calls  \
0                      0              184.5               97   
1                      0              129.1              137   
2                      0              332.9               67   
3                      0              110.4              103   
4                      0              119.3              117   

   Total day charge  Total eve minutes  Total eve calls  Total eve charge  \
0             31.37              351.6               80             29.89   
1             21.95              228.5               83             19.42   
2             56.59              317.8               97             27.01   
3             18.77              137.3              102             11.67   
4             20.28              215.1              109             18.28   

   Total night minutes  Total night calls  Total night charge  \
0                215.8                 90                9.71   
1                208.8                111                9.40   
2                160.6                128                7.23   
3                189.6                105                8.53   
4                178.7                 90                8.04   

   Total intl minutes  Total intl calls  Total intl charge  \
0                 8.7                 4               2.35   
1                12.7                 6               3.43   
2                 5.4                 9               1.46   
3                 7.7                 6               2.08   
4                11.1                 1               3.00   

   Customer service calls  Churn  
0                       1  False  
1                       4   True  
2                       4   True  
3                       2  False  
4                       1  False

In [ ]:
print(test_data["International plan"].unique())
print(test_data["Voice mail plan"].unique())
print(test_data["Churn"].unique())

['No' 'Yes']
['No' 'Yes']
[False  True]


## Feature Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
test_data["International plan"] = le.fit_transform(test_data["International plan"])
test_data["Voice mail plan"] = le.fit_transform(test_data["Voice mail plan"])
test_data["Churn"] = le.fit_transform(test_data["Churn"])

In [ ]:
temp = pd.get_dummies(test_data["State"])
test_data = pd.concat([test_data, temp],axis=1)
test_data.drop(["State"], axis = 1, inplace = True)

## Feature Scaling

In [ ]:
scale_col = test_data.drop(unq_states, axis = 1).columns
test_data[scale_col] = scaler.fit_transform(test_data[scale_col])

## Spliting Data

In [ ]:
X_test = test_data.iloc[:, :-1].values
y_test = test_data.iloc[:, -1].values

In [ ]:
testing_result = model.predict(X_test)

## Test Results

In [ ]:
cm = confusion_matrix(y_test, testing_result)
acc = accuracy_score(y_test, testing_result)

print(f"TESTING RESULTS : \n {cm} \n Accuracy : {acc*100}%")

TESTING RESULTS : 
 [[656   0]
 [ 11   0]] 
 98.35082458770614%
